GFTproject/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('administracao/', admin.site.urls),
    path('',include('permission.urls')),
    path('autores/',include('authors.urls')),
]

authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'

urlpatterns = [
    path('registro/', views.register_view, name='register'),
    path('registro/criar/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/criar/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
]

permission/urls.py
from django.urls import path
from . import views

app_name = 'permission'

urlpatterns = [
    path('', views.home, name='home'),
    path('permissao/search/', views.search, name='search'),
    path('permissao/interdiction/<int:interdiction_id>/', views.interdiction, name='interdiction'),
    path('permissao/<int:id>/', views.permissionview, name='permission'),
]

permission/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Interdiction(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Permission(models.Model):
    slug = models.SlugField(unique=True)
    location = models.CharField(max_length=65)
    lat = models.CharField(max_length=15, null=True)
    lon = models.CharField(max_length=15, null=True)
    description = models.CharField(max_length=65)
    order = models.CharField(max_length=65)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_register = models.DateField()
    reason = models.ForeignKey(
        Interdiction, on_delete=models.SET_NULL, null=True,
        blank=True, default=None
        )
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    authorized = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.reason} na {self.location} solicitado por {self.author}'

permission/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import Http404
#from utils.permission.factory import make_permission
from .models import Permission
from utils.pagination import make_pagination

import os

PER_PAGE = int(os.environ.get('PER_PAGE', 6))

def home(request):
    permissions = Permission.objects.filter(
            authorized=True
        ).order_by('date_start')
      
    pag_obj, pagination_range = make_pagination(request, permissions, PER_PAGE)

    return render( request, 'permission/pages/home.html', context={
        'permissions':pag_obj,
        'pagination_range': pagination_range,
        })

def interdiction(request, interdiction_id):
    permissions = get_list_or_404(
        Permission.objects.filter(
            reason__id=interdiction_id,
            authorized=True
        ).order_by('date_start')
        )
    
    pag_obj, pagination_range = make_pagination(request, permissions, PER_PAGE)

    return render( request, 'permission/pages/interdiction.html', context={
        'permissions': pag_obj,
        'pagination_range': pagination_range,
        'title': f'{permissions[0].reason.name} - Interdição | ',
        })

def permissionview(request,id):
    permission = get_object_or_404(Permission, pk=id, authorized=True)
       
    return render(request, 'permission/pages/permissionview.html', context={
    'permission':permission,
    'is_detail_page': True,
    })

def search(request):
    search_term = request.GET.get('q','').strip()
    if not search_term:
        raise Http404('Termo de busca não encontrado.')
    
    permissions = Permission.objects.filter(
        authorized=True,
        location__icontains=search_term,
    ).order_by('date_start')

    pag_obj, pagination_range = make_pagination(request, permissions, PER_PAGE)


    return render(request, 'permission/pages/search.html',
                  {
                      'page_title': f'Busca por "{search_term}" | ',
                      'search_term': search_term,
                      'permissions':pag_obj,
                      'pagination_range': pagination_range,
                      'additional_url_query': f'&q={search_term}',
                  }
                  )

permission/templates/permission/partials/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css" integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css" integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css" integrity="sha512-DzC7h7+bDlpXPDQsX/0fShhf1dLxXlHuhPBkBo/5wJWRoTU6YL7moeiNoej6q3wh5ti78C57Tu1JwTNlcgHSjg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'permission/css/styles.css' %}">

permission/templates/permission/partials/permission.html
<div class="permission permission-list-item">
    <div class="permission-cover">
        <div id='map{{ permission.id }}' style="height: 350px;"></div>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
        crossorigin=""/>
        <!-- Make sure you put this AFTER Leaflet's CSS -->
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
        crossorigin=""></script>
      
        <script>
            document.addEventListener('DOMContentLoaded', function() {

                var lat = -20.524820;
                var lng = -54.599175;

                {% if permission.lat is not None %}
                    lat = {{ permission.lat }};
                {% endif %}
                {% if permission.lon is not None %}
                    lng = {{ permission.lon }};
                {% endif %}

                var map = L.map('map{{ permission.id }}').setView([lat, lng], 17);
                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                }).addTo(map);
                L.marker([lat, lng]).addTo(map);
            });
        </script>
    </div>
    <div class="permission-title-container">
        {% if is_detail_page is not True %}
        <a href='{% url 'permission:permission' permission.id %}'>
        {% endif %}
            <h2 class="permission-title"> Local: {{permission.location}}</h2>
        {% if is_detail_page is not True %}
        </a>
        {% endif %}
        <br>
        <h3 class="permission-subtitle">
            {{permission.description}}
        </h3>
    </div>
    <div class="permission-author">
        <span class="permission-author-item">
            <i class="fa-solid fa-file-import"></i>
            <span>Pedido: {{permission.order}}</span>
        </a>
        </span>
        <br>
        {% if permission.author is not None %}
            <span class="permission-author-item">
                <i class="fas fa-user"></i>
                {{permission.author.first_name}} {{permission.author.last_name}}
            </span>
        {% endif %}
        <br>
        {% if permission.reason.id is not None %}
            <span class="permission-author-item">
                <a href='{% url 'permission:interdiction' permission.reason.id %}'>
                    <i class="fas fa-layer-group"></i>
                    <span>{{ permission.reason }}</span>
                </a>
            </span>
        {% endif %}
    </div>
    <div class="permission-meta-container">
        <div class="permission-meta permission-preparation">
            <h3 class="permission-meta-title"><i class="fas fa-stopwatch"></i> Início</h3>
            <div class="permission-meta-text">
                {{ permission.date_start|date:"d/m/Y" }} às {{ permission.date_start|date:"H:i" }}
            </div>
        </div>
        <div class="permission-meta permission-servings">
            <h3 class="permission-meta-title"><i class="fa-solid fa-bell"></i> Fim</h3>
            <div class="permission-meta-text">
                {{ permission.date_end|date:"d/m/Y" }} às {{ permission.date_end|date:"H:i" }}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
        <footer class="permission-footer">
            <a class="permission-read-more button button-dark button-full-width" href="{% url 'permission:permission' permission.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
</div>

permission/templates/permission/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'permission:search' %}" method="GET" class="search-form" >
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button" ><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>